http.host: 0.0.0.0

#xpack.security.enabled: false


# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1

# 디스크 관리기능 중지 => qtie scheduler 에서 관리함
cluster.routing.allocation.disk.threshold_enabled: false
