version: '2'

services:
  test-ls-es:
    restart: always
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    container_name: test-ls-es
    depends_on:
      - test-kf-es
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/env/:/usr/share/logstash/env/
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
    ports:
      - 30524:514
      - 30525:515
      - 30526:516
      - 30527:517

  test-es:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    container_name: test-es
    environment:
      - cluster.name=qtie
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms6G -Xmx6G"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 19202:9200
      - 19602:9600

  test-kb-es:
    restart: always
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    container_name: test-kb-es
    depends_on:
      - test-es
    ports:
      - "15602:5601"
    environment:
      - "SERVER_NAME=qtie"
      - "ELASTICSEARCH_URL=http://test-es:9200"

  test-zk-es:
    restart: always
    image: wurstmeister/zookeeper
    container_name: test-zk-es
    ports:
      - "12182:2181"

  test-kf-es:
    restart: always
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: test-kf-es
    depends_on:
      - test-zk-es
    ports:
      - "19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://test-kf-es:9092
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "case_1:1:1,case_2:1:1,case_3:1:1,case_4:1:1"
      KAFKA_ZOOKEEPER_CONNECT: test-zk-es:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_LOG_CLEANER_ENABLE: 'true'
      KAFKA_LOG_CLEANUP_POLICY: 'delete'
      KAFKA_LOG_RETENTION_MS: 86400000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 3600000
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_RETENTION_BYTES: 10737418240
      KAFKA_LOG_SEGMENT_BYTES: 1073741824

networks:
  default:
    external:
      name: test-es

